import type { Metadata } from 'next';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      {/* <AuthHeader /> */}
      <main>{children}</main>
      {/* <AuthFooter /> */}
    </div>
  );
};

export default AuthLayout;
