import type { Metadata } from 'next';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="relative flex flex-col justify-start items-center min-h-screen">
      <Header />
      <main className="w-full py-16 md:py-24 min-h-screen max-w-screen-xl">
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default MainLayout;

// px-4 md:px-12 lg:px-24
